# Netflix Exploratory Data Analysis

### Data Cleaning

Importing required libraries.

In [313]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

Loading the data into the dataframe.

In [314]:
df = pd.read_csv("netflix_titles.csv")

In [315]:
df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

Checking data types and changing it if necessary.

In [316]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8807 entries, 0 to 8806
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8807 non-null   object
 1   type          8807 non-null   object
 2   title         8807 non-null   object
 3   director      6173 non-null   object
 4   cast          7982 non-null   object
 5   country       7976 non-null   object
 6   date_added    8797 non-null   object
 7   release_year  8807 non-null   int64
 8   rating        8803 non-null   object
 9   duration      8804 non-null   object
 10  listed_in     8807 non-null   object
 11  description   8807 non-null   object
dtypes: int64(1), object(11)
memory usage: 825.8+ KB

In [317]:
df['date_added'] = pd.to_datetime(df['date_added'], errors='coerce')

Checking for duplicates.

In [318]:
duplicate_rows_df = df[df.duplicated()]
print("number of duplicate rows: ", duplicate_rows_df.shape)
# no duplicates, yay!

number of duplicate rows:  (0, 12)

Rearranging data and renaming columns.

In [319]:
df = df.rename(columns={'show_id': 'title_id', 'listed_in': 'genres'})
df.head()

,title_id,type,title,director,cast,country,date_added,release_year,rating,duration,genres,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,2021-09-25,2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,2021-09-24,2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,2021-09-24,2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,2021-09-24,2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,2021-09-24,2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

In [320]:
# Extract minutes
df['minutes'] = df['duration'].str.extract(r'(\d+)\s*min', expand=False)
df['minutes'] = df['minutes'].fillna(0).astype(int)

# Extract seasons
df['seasons'] = df['duration'].str.extract(r'(\d+)\s*Season', expand=False)
df['seasons'] = df['seasons'].fillna(0).astype(int)

# delete duration column
df = df.drop(columns=['duration'])

df.head()

,title_id,type,title,director,cast,country,date_added,release_year,rating,genres,description,minutes,seasons
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,2021-09-25,2020,PG-13,Documentaries,"As her father nears the end of his life, filmm...",90,0
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,2021-09-24,2021,TV-MA,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t...",0,2
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,2021-09-24,2021,TV-MA,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...,0,1
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,2021-09-24,2021,TV-MA,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo...",0,1
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,2021-09-24,2021,TV-MA,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...,0,2

Handling null values.

In [321]:
print('total rows: ' + str(len(df)))

total rows: 8807

In [322]:
df.isnull().sum().sort_values(ascending=False)

director        2634
country          831
cast             825
date_added        98
rating             4
title_id           0
type               0
title              0
release_year       0
genres             0
description        0
minutes            0
seasons            0
dtype: int64

In [323]:
# Handling nulls in director column
df['director'] = df['director'].fillna('Missing Director')

# Handling unknown countries
df['country'] = df['country'].fillna('Unknown')

df.head()

,title_id,type,title,director,cast,country,date_added,release_year,rating,genres,description,minutes,seasons
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,2021-09-25,2020,PG-13,Documentaries,"As her father nears the end of his life, filmm...",90,0
1,s2,TV Show,Blood & Water,Missing Director,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,2021-09-24,2021,TV-MA,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t...",0,2
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",Unknown,2021-09-24,2021,TV-MA,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...,0,1
3,s4,TV Show,Jailbirds New Orleans,Missing Director,NaN,Unknown,2021-09-24,2021,TV-MA,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo...",0,1
4,s5,TV Show,Kota Factory,Missing Director,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,2021-09-24,2021,TV-MA,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...,0,2

### Data Analysis

Extract unique genres for each title.

In [324]:
genres = df[["title_id", "genres"]].copy()

genres.head()

  title_id                                             genres
0       s1                                      Documentaries
1       s2    International TV Shows, TV Dramas, TV Mysteries
2       s3  Crime TV Shows, International TV Shows, TV Act...
3       s4                             Docuseries, Reality TV
4       s5  International TV Shows, Romantic TV Shows, TV ...

In [325]:
genres["genres"] = genres["genres"].str.split(",")
genres = genres.explode("genres")

genres.head()

  title_id                  genres
0       s1           Documentaries
1       s2  International TV Shows
1       s2               TV Dramas
1       s2            TV Mysteries
2       s3          Crime TV Shows

Extract unique countries for each title.

In [326]:
countries = df[["title_id", "country"]].copy()

countries.head()

  title_id        country
0       s1  United States
1       s2   South Africa
2       s3        Unknown
3       s4        Unknown
4       s5          India

In [327]:
countries["country"] = countries["country"].str.split(",")
countries = countries.explode("country")

countries.head()

  title_id        country
0       s1  United States
1       s2   South Africa
2       s3        Unknown
3       s4        Unknown
4       s5          India

Get titles associated with each country.

In [330]:
titles_per_country = countries.groupby("country")["title_id"].count()
print(titles_per_country.sort_values(ascending=False))

country
United States     3211
India             1008
Unknown            831
United Kingdom     628
 United States     479
                  ...
Mozambique           1
Namibia              1
 Latvia              1
 Kuwait              1
Zimbabwe             1
Name: title_id, Length: 198, dtype: int64